# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/student/Desktop/project2-gurkan-demir-2015400177-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/student/Desktop/project2-gurkan-demir-2015400177-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/Desktop/project2-gurkan-demir-2015400177-master/CMakeFiles /home/student/Desktop/project2-gurkan-demir-2015400177-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/Desktop/project2-gurkan-demir-2015400177-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project2

# Build rule for target.
project2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project2
.PHONY : project2

# fast build rule for target.
project2/fast:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/build
.PHONY : project2/fast

Bar.o: Bar.cpp.o
.PHONY : Bar.o

# target to build an object file
Bar.cpp.o:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Bar.cpp.o
.PHONY : Bar.cpp.o

Bar.i: Bar.cpp.i
.PHONY : Bar.i

# target to preprocess a source file
Bar.cpp.i:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Bar.cpp.i
.PHONY : Bar.cpp.i

Bar.s: Bar.cpp.s
.PHONY : Bar.s

# target to generate assembly for a file
Bar.cpp.s:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Bar.cpp.s
.PHONY : Bar.cpp.s

Cash.o: Cash.cpp.o
.PHONY : Cash.o

# target to build an object file
Cash.cpp.o:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Cash.cpp.o
.PHONY : Cash.cpp.o

Cash.i: Cash.cpp.i
.PHONY : Cash.i

# target to preprocess a source file
Cash.cpp.i:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Cash.cpp.i
.PHONY : Cash.cpp.i

Cash.s: Cash.cpp.s
.PHONY : Cash.s

# target to generate assembly for a file
Cash.cpp.s:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Cash.cpp.s
.PHONY : Cash.cpp.s

Customer.o: Customer.cpp.o
.PHONY : Customer.o

# target to build an object file
Customer.cpp.o:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Customer.cpp.o
.PHONY : Customer.cpp.o

Customer.i: Customer.cpp.i
.PHONY : Customer.i

# target to preprocess a source file
Customer.cpp.i:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Customer.cpp.i
.PHONY : Customer.cpp.i

Customer.s: Customer.cpp.s
.PHONY : Customer.s

# target to generate assembly for a file
Customer.cpp.s:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/Customer.cpp.s
.PHONY : Customer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/project2.dir/build.make CMakeFiles/project2.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... project2"
	@echo "... rebuild_cache"
	@echo "... Bar.o"
	@echo "... Bar.i"
	@echo "... Bar.s"
	@echo "... Cash.o"
	@echo "... Cash.i"
	@echo "... Cash.s"
	@echo "... Customer.o"
	@echo "... Customer.i"
	@echo "... Customer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

